services:
  pokedexapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${PAGINATION_DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/pokedex
    networks:
      - mynetwork

  db:
    image: mongo
    container_name: mongo-poke
    restart: always
    ports:
      - 2300:27017
    environment:
      MONGO_INITDB_DATABASE: nest-pokemon
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    # volumes:
    #     - ./mongo:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge